### ISSUE TITLE
Route Issue

### ISSUE THREAD

**Issue by Benrobo** [princecodes247/veldora#4]
**Describe the bug**
After clicking on the collection created, the link provided was having a routine issue i.e 
https://veldora.herokuapp.com/collections/send/vel930525Loc

cannot get Cannot GET /collections/send/vel930525Loc

**Comment by princecodes247** [comment]
Hi! I believe the problem here is lack of information.

You're supposed to use that link in your forms, not click on it.
In further updates we'll try better to pass the instructions

**Comment by princecodes247** [comment]
Don't forget to star the project

**Comment by Benrobo** [comment]
when the link  used within the form, would it not be receiving a post
request? or not. that why that error shows.

**Comment by princecodes247** [comment]
You are meant to send a post request to the route in question

**Comment by Benrobo** [comment]
kk
